spring:
  cas:
    sign-out-filters: /logout
    auth-filters: /*
    validate-filters: /*
    request-wrapper-filters: /*
    assertion-filters: /*
    cas-server-login-url: http://localhost:8088/cas/login
    cas-server-url-prefix: http://localhost:8088/cas
    redirect-after-validation: true
    use-session: true
    server-name: http://localhost:8080